# API Documentation Routes - Imported first to take priority
api_doc:
    resource: routes/api_doc.yaml
    prefix: ''

#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_logout:
    path: logout
    methods: GET
